[project]
name = "task1-cnn"
version = "0.1.0"
description = "CNN classifier for FashionDataset"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.0.0",
    "opencv-python-headless>=5.0.0.93",
    "pandas>=3.0.5",
    "scikit-learn>=1.6.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]
